- name: Create pods using deployment 
  hosts: kubernetes 
  # become: true
  # user: ubuntu
 
  tasks: 
  - name: delete the previous deployment
    command: kubectl delete deployment.apps/cicd-deployment
    ignore_errors: yes

  - name: create a deployment
    command: kubectl apply -f cicd-devops-deployment.yml